update planetscope scripts
sentinel-hub/custom-scripts pull request #308
Opened 2024-04-10 11:17 UTC by zcernigoj

2024-05-28 14:34 UTC, chorng requested changes
Add some comments for minor changes.

2024-06-05 19:42 UTC, matthew-ballard commented
hi @chorng and @zcernigoj , I just submitted #317 before seeing #308, are you planning to merge this one? or would you be interested in consolidating the two PRs? There is some overlap

2024-06-06 07:22 UTC, zcernigoj commented
Hey @matthew-ballard 
I missed the review from @chorng , let me make the changes and merge, and then you can include the updates in your PR.

I guess that would be easiest.

2024-06-06 09:40 UTC, zcernigoj commented on planet_scope/ndwi/eob.js
> +  let id_default = colorBlend(ndwi,
Thanks, removed it and added it only in the return statement

2024-06-06 09:41 UTC, zcernigoj commented on planet_scope/ndwi/script.js
> +  let id_default = colorBlend(ndwi,
Thanks, removed it and added it only in the return statement

2024-06-06 09:41 UTC, zcernigoj commented on planet_scope/ndwi/script.js
> +function evaluatePixel(samples) {
Thanks, renamed it to `sample`

2024-06-06 09:42 UTC, zcernigoj commented on planet_scope/ndwi/script.js
> +  return { default: id_default };
I decided to use `[...id_default, sample.dataMask]`

2024-06-06 09:42 UTC, zcernigoj commented on planet_scope/ndwi/raw.js
> +    input: [{ bands: ["green", "nir", "dataMask"] }],
Thanks, removed.

2024-06-06 09:42 UTC, zcernigoj commented on planet_scope/ndwi/raw.js
> +function evaluatePixel(samples) {
Thanks, renamed it to `sample`

2024-06-06 09:42 UTC, zcernigoj commented on planet_scope/ndwi/raw.js
> +  return {default: [ndwi]};
Thanks, used the suggested code

2024-06-06 09:42 UTC, zcernigoj commented on planet_scope/ndwi/eob.js
> +function evaluatePixel(samples) {
Thanks, renamed it to `sample`

2024-06-06 09:43 UTC, zcernigoj commented on planet_scope/ndwi/eob.js
> +    default: id_default,
I decided to use [...id_default, sample.dataMask]

2024-06-06 09:43 UTC, zcernigoj commented on planet_scope/ndwi/eob.js
> +  const indexVal = samples.dataMask === 1 ? ndwi : NaN;
Thanks, added the check for infinite number

2024-06-12 08:10 UTC, merged